export const utilities = [
  { name: "Tailwind Color Guide", url: "/palette" },
  { name: "JavaScript Playground", url: "/javascriptplayground" },
  { name: "Image to Text Converter", url: "/imagetotext" },
  { name: "PDF to Word Converter", url: "/pdftowordconverter" },
  { name: "Resume Builder", url: "/resumebuilder" },
  { name: "Mesh Gradient Generator", url: "/meshgenerator" },
  { name: "Screen Recorder", url: "/screenrecorder" },
  { name: "Image Editor", url: "/imageeditor" },
  { name: "Scale Mapper", url: "/scalemapper" },
  { name: "Metronome", url: "/metronome" },
  { name: "Tuner", url: "/tuner" },
  { name: "Planner", url: "/planner" },
  { name: "Todo List", url: "/todo" },
  { name: "Gallery", url: "/gallery" },
  { name: "Box Shadow Generator", url: "/boxshadowgenerator" },
];
